### ISSUE TITLE
What do I do after executing to_anytype.py script?

### ISSUE THREAD

**Issue by csdjk** [mishachepi/obsidian-to-anytype#1]
What do I do after executing to_anytype.py script? Manually import files one by one?

**Comment by mishachepi** [comment]
You need to import root of obsidian workspace to AnyType as markdown files
AnyType -> file -> Import -> Markdown -> obsidian workspace root

**Comment by csdjk** [comment]
> You need to import root of obsidian workspace to AnyType as markdown files AnyType -> file -> Import -> Markdown -> obsidian workspace root

Only a single markdown file can be imported. If the Obsidian workspace is packaged into a .zip file for import, each imported file will not have the correct title.

**Comment by mishachepi** [comment]
<img width="542" alt="Screenshot 2024-03-14 at 13 59 09" src="https://github.com/mishachepi/obsidian-to-anytype/assets/70561854/d1bc3b61-d583-4339-984e-4202722efb5a">

<img width="880" alt="Screenshot 2024-03-14 at 13 59 27" src="https://github.com/mishachepi/obsidian-to-anytype/assets/70561854/552d96d9-f13e-4bfa-9e99-5b3df81b3019">
And choose the folder
<img width="722" alt="Screenshot 2024-03-14 at 13 59 56" src="https://github.com/mishachepi/obsidian-to-anytype/assets/70561854/567a02f3-c8e2-4135-a33c-1347ac4eaa97">
